### ISSUE TITLE
Reading soybean data

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#103]
The soybean data provided by Sotirios is in a completely different format to the data REMS has been working with so far, and will not work with the current importer.

In its current form, it appears similar to what we expect from a 'Data' template, though the trait data is spread out across more tables, with none of the expected Information/Experiments scaffolding explicitly presented (though it should be possible to create that data by working backwards from what *is* present)

The options are to either manually edit the .xslx into the expected format, which would be more sensible if this is the only set of data formatted in this manner, otherwise a new importer function will need to be written.

**Comment by jbrider** [comment]
you will need to extract the relevant data to create the first 2 import templates.
Let us know if you need help with it.

**Comment by MikeStower** [comment]
That's the point I'd gotten to after looking at it - it shouldn't be too difficult from what I can see, just a bit tedious.

**Comment by MikeStower** [comment]
Completed in recent pull requests
