### ISSUE TITLE
Enforce required columns on spreadsheet import

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#145]
If the importer does not detect the expected columns, it should block the import and alert the user to correct the file.

**Comment by MikeStower** [comment]
After reading in the spreadsheet data, the importer present following behaviour for each table in the document:
- A 'required' child node, listing all the expected columns that REMS needs to import
- Required nodes can be valid, if a matching column has been detected, or invalid, if no column is found
- Missing required nodes will block the import
- A 'traits' child node, listing all other columns found in the table
- Trait nodes are valid, if a matching trait in the database is found, or invalid, if none are present
- Invalid traits will NOT block the import, REMS will assume any unknowns are to be added as traits

**Comment by MikeStower** [comment]
Working on this in 664a478 - the aim is to have all the expected columns in a spreadsheet have a corresponding property on an entity, which is marked with an attribute. Columns that are used during the import, but are not present on the schema (such as Experiments.SiteName) can be marked with EFCores NotMapped attribute to prevent them from being entered in the DB.

The entities themselves are being marked with an attribute specifying which excel sheet their corresponding table is expected to be found in. Then, in the import, to find all the required nodes for the import, all the entities that are marked as being required for that sheet are found, as are the expected columns. This eliminates the need for a lookup table or any direct string comparison, if any of the marked tables and columns that REMS expects are not found in the loaded sheet, an error can be output.

**Comment by MikeStower** [comment]
Continuing the previously described process in 1785aa829a2628f1edafa9505d415684b7dc0b75.

**Comment by jbrider** [comment]
I'll be honest and say my first reaction was that this would be overly
complicated... and more time intensive to setup than a simple lookup table.
Given the emphasis on getting it working in the short term, I would suggest
it may not have been the right solution...
but...
It does look like a good long term solution - and a useful technique for
other projects.
Please make sure you have some comments around it to make it clear how it
works - fancy solutions are often the hardest ones to maintain - ie: when I
come back in 6 months will someone else be able to  work out how it works.
I'm familiar with NotMapped but haven't seen 'expected' used before.
Therefore this is probably a feature that should be documented in the
readme.md.

The comments are working really well - particularly the links.

**Comment by MikeStower** [comment]
This might be my proclivity for fancy language working against me - I put some thought into this and I'm fairly certain it's actually the easiest way to do it. 

Step by step approach:
 - Expected is a custom attribute
 - Every required column in excel has a property on an entity attributed with 'Expected'
 - To import a table, we look at all the Expected properties, and demand the user provide columns that match
 - Properties such as Experiment.SiteName, which are necessary in Excel but not in the schema are attributed with NotMapped, to prevent them appearing in the DB

It's fundamentally just a lookup table matching schema properties to excel columns, but implemented through attributes.

**Comment by MikeStower** [comment]
Added more information to attributes in 4cab27745df0ebc47c6b91f148d1986999f79c6a.

Began working on the new importer treeview in c2b3cb4a4c55e7915b8ef34592fbb2a66354310e. Presently the new nodes are being included alongside the old ones to allow for a comparison. A node is created for each expected table, and child nodes are added for each expected property in the table. The importer looks through the dataset and tries to find tables and columns that match the expected ones. This is inverse to the old approach, which populated the nodes based on the contents of the dataset.

The new system works as expected when it succesfully matches a component of the dataset to what it expects, but currently has no handling for situations where it does not find a match, which is the next goal.

**Comment by MikeStower** [comment]
Removed old validation process in 90c6ee629249736cddfc3ecb0f62287d26aafea7, as it is no longer required. Also cleaned up the context menu options available to nodes.

**Comment by MikeStower** [comment]
Expanded the revised import to include experiments sheets in 4d8e8a58612216c0462fa279dd8433672a947b7b.

**Comment by MikeStower** [comment]
Improved the context menu options for nodes in 4d997c9e756a78303fd327024458966a0b5aa419.

**Comment by MikeStower** [comment]
Added attributes for Data entities in ade8bd4eb30ec8fa36455beb0c5c361efc574a0b, and now have the same functionality as prior to the import rework.

**Comment by MikeStower** [comment]
Made import easier in 2718701d10b6c66370cdeb9cc256ad707fd2a29a.

**Comment by MikeStower** [comment]
Fixed the treeview behaviour in fa69a1765c451a2e5eec78f6522b5f8ca58ada5d. Last change for import is to include more obvious tooltips / make it more explicit to the user why the import is blocked by missing required nodes.

**Comment by MikeStower** [comment]
Made requirements more obvious to users in 180b3efed0c788e45edce46b1f302a88d732e978

**Comment by MikeStower** [comment]
Improved context menu clarity fec39fc527048df818eadff976bb8646eda4a357

**Comment by MikeStower** [comment]
Resolved in #151
