### ISSUE TITLE
Experiment detailer should display met data

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#200]
It should show alongside the operations/crop/soil nodes.

**Comment by MikeStower** [comment]
@jbrider how do we want the data displayed? I thought a good starting point might be to just mirror the weather model from NG.

**Comment by jbrider** [comment]
That sounds like a good starting point.

**Comment by MikeStower** [comment]
Working on this in 997c6ee33fa945695fc196fc07f6032711904224
