### ISSUE TITLE
.met file export might need adjusting

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#210]
Presently, exported simulations are runnable if they have a valid .met file. This requires valid met data in the database (which can be checked by looking for data between the start and end date of the experiment). 

However, there are cases where valid data exists over the required range, and even though APSIM can find and display the data,

![image](https://user-images.githubusercontent.com/53413135/127100009-ea9896d0-c3eb-4656-8483-96dce91b24e2.png)

it throws an error when attempting to run the simulation,

![image](https://user-images.githubusercontent.com/53413135/127098410-6ed62ac2-497e-466d-ad47-eb058724261e.png)

I've done some searching and suspect it's actually a bug in APSIM but I'm not sure what the cause is. Some of the REMS generated .met files work as expected. Swapping out one of the faulty REMS generated .met files for an existing .met file that covers the required range is enough to let the simulation run. I havve been unable to determine the distinction between working and broken REMS .met files - they all export the same.

**Comment by jbrider** [comment]
Have you got an example of a not working file, and the file you used to get it working?

**Comment by MikeStower** [comment]
Here's a REMS generated .apsimx file with two met files, one that works with the simulation and one that doesn't.
[metExamples.zip](https://github.com/QAAFI/REMS2020/files/6889284/metExamples.zip)

**Comment by MikeStower** [comment]
Resolved in #212
