### ISSUE TITLE
Need to refactor WindowsClient into Infrastructure Layer

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#224]
The infrastructure layer was temporarily removed to fix bugs / structural issues, but now that those earlier problems have been resolved it should be reintroduced.

**Comment by MikeStower** [comment]
Working on this in 
- 73ec177efaf8ca963612ec37b3eb372c2994dcb9
- fa906019ff081e29c42145d63052c6514604d700
- dd631d5a891395014b20287dc1b72afde3d508c0
- 0a0e26df1154d5739795f9d2a368249527745f53

**Comment by MikeStower** [comment]
@jbrider Just wanted to clarify the goals of the refactor:
1. There should be as little logic as possible in the Presentation layer, only UI components
2. The Presentation layer should not need to reference the Application layer, only the Infrastructure layer
3. The Infrastructure layer needs to be entirely cross-platform

**Comment by jbrider** [comment]
That seems to be correct - weI should be able to drop the back end code onto a web site and it should still work.

**Comment by MikeStower** [comment]
Working on this in:
- 7d4e950e8d5010de9d2931373d238be2d198b113
- eb8d0bb0b2ea410df35b2bff87027d3e363b8aa4
- 57782fb9c1168ff6f61e56295451f39e9e7e1306

**Comment by MikeStower** [comment]
I've been doing some reading on DDD and considering the structure of the code, and I want to review one of the goals of the refactor. Based on these readings, I'm now thinking to revise goal 2. It may be acceptable for the Presentation layer to reference the Application layer. While there are many schools of thought on how the layers in DDD should be organised, a majority of them have the Presentation layer dependent on both the Infrastructure and Application layers, not just one or the other.

My new understanding is that:
1. The Application layer is, fundamentally, an interface to the Domain layer
2. The Infrastructure layer is an implementation of the interfaces in the Application layer
3. The Presentation layer is how a user interacts with the Infrastructure layer

While the Infrastructure should contain most of the concrete logic, certain interfaces make more sense to implement directly in the presentation layer, such as requests that require user confirmation. With this in mind I don't think I should completely remove all references to the Application layer from the Presentation.

**Comment by jbrider** [comment]
The implementation of the CQRS means that we're not using a traditional DDD concept as in concept it is able take a slice through the layers if necessary - except for the presentation layer. What it can't be is across the presentation layer as well in order to be able to utilise different UI's.  That said - our implementation hasn't really had to do that.
Philosophical questions are all well and good and great for a brain storming session, but what is it that you need to keep in the gui from the application layer?

**Comment by MikeStower** [comment]
I think the only things that make use of  UI-Application linking are queries that require user confirmation or input, typically during the import but potentially during the export as well (for example if we refine the handling of soil models further). Some queries will run into situations that they don't know how to handle, in which case a dialog or popup requests the user for some input. In those cases, it makes more sense to me to go directly to the UI from the Application, rather than routing that request through the Infrastructure.

**Comment by jbrider** [comment]
If that's the only reason then you're looking at it the wrong way.  Your code should be able to run without any user interaction - you should be able to pass configuration to handle different scenarios.  Your user interaction is then building that configuration in a series of smaller steps. ie: To output an apsim file that has no met data you should be able to pass a config that says ignore the met output.  The question to the user is a request what to do if the met file is missing - that has nothing to do with the implementation of the output process - it is a check done before the output can occur. To improve the user experience you could store that response for that experiment so you don't keep asking it.  The UI can then show that the met will be skipped during the output process the next time without asking the user again.

**Comment by MikeStower** [comment]
Working on this is b1a2cece770793f32e396aafe887f0d8fac28fde.

On top of the advantages described in the commit, using the inbuilt System.Data classes for populating the UI charts means we need less custom classes of our own, and simplifies the inter-layer dependencies more. Once the charts are set up to use the new queries, their logic will be able to be moved into the Infrastructure layer, removing another dependency the Presentation layer has on the Application layer.

**Comment by MikeStower** [comment]
Working on this in 4beff03bc8b71b464ccd49cfca2bbab52cc4a1fd

**Comment by MikeStower** [comment]
Removed last dependencies on the Application layer from the chart controls in
- 55a1ae750074ac2e6aa3d64217363585c9f33f65
- c6bf9f552b3a1a1276b6e86dc2eeb4362cb190dc
- a4f507c64610d2083563369c4edf112d59433727
- c5be5d59c956bf5c1626a91402c56cea95b41269
