### ISSUE TITLE
Exported simulations need panel graph included

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#246]

**Comment by MikeStower** [comment]
@jbrider Should the traits displayed in these graphs be a static set or dynamically chosen? 

Looking at the Hermitage sorghum example, there's a set of 9 traits displayed in the predicted-observed graphs. However, those traits might not always be included among the observed data (such as in the FACTS soybean experiment). Is it a requirement of these style of graphs that those 9 particular traits are always the ones displayed, or can we use a selection of any traits from the observed data?

**Comment by jbrider** [comment]
They're the desired traits - if they're missing then it says the dataset is missing some key data.
So we should either let them know they're missing useful data, or create a subset to suit their data.
You need to present as a list of missing traits for Greg/Graeme to decide where to take it next.

**Comment by MikeStower** [comment]
Looking at it again, I think I've misrepresented / misunderstood the problem. It's not so much that the data is missing but take it may be recorded differently. For example, sorghum uses grain number whereas soybean uses number of pods. They're distinct traits that represent the same concept.

Another example might be that the graphs use total biomass nitrogen, which can easily be calculated from the soybean data, but has not been recorded as its own trait / column.

My first approach to handling this would probably be the same as other missing data - do a naive search for those 9 traits and if they're not found, inform the user through the export summary.
