### ISSUE TITLE
Experiment IDs in data may not be unique, cannot be used as primary key

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#34]
While the ID in a solitary dataset should be unique, it is not suitable to be a primary key, as other, independent, datasets could also potentially use that same ID. Further, since many tables in that dataset often refer only to the ExperimentId. Since the table imports are largely independent of each other, this could cause issue during import, as it may not be clear which experiment the Id field is referring to. To resolve this issue without breaking the current import functionality

1. The schema must be updated so that the primary key for an experiment is a combination of the ExperimentId and Name fields
2. During the data preparation phase prior to import, all columns in all tables which reference the ExperimentId must instead be made to reference the experiment entity directly, this can be managed by
    1. Requiring the dataset to have an experiments table
    2. Finding or creating database entries for each experiment in the dataset
    3. Substituting the all columns which refer to ExperimentId with a DataColumn that references the Experiment entity directly
3. The importer must be updated to handle DataColumn objects which reference entities, which has two parts
    1. The generic table import, which currently assumes each column holds value data
    2. Each custom table import, some of which rely on the assumption that certain columns hold ExperimentId data

By following this process, by the time the actual import occurs, each table should be able to uniquely identify the experiments referenced.

**Comment by MStowerUQ** [comment]
These suggested changes won't work, as changing the primary key of the Experiments table will break the current one-to-many relations dependent on that key. Instead, uniqueness of an experiment will be determined solely by the experiment name, which will be checked against all experiments currently in the database. A unique ExperimentId key will be generated upon adding the entity to the DB. 

Any ExperimentId values in a DataSet will only be used to relate experiments across that DataSet, and will not be imported (still making use of the find + replace method described above).
