### ISSUE TITLE
Dates are displayed with time component

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#40]
Should the time be hidden? Or do we want to leave the possibility of hourly measurements available.

**Comment by jbrider** [comment]
Good question.  Is this in the observations list when dates are present?

**Comment by MikeStower** [comment]
This is everywhere that displays a table through a gridview. I have a generic function that formats a gridview to display correct decimals, fix alignments etc. The default handling for columns with dates is leaving the time visible as 00:00:00 for all entries.

**Comment by MikeStower** [comment]
It has been decided that this is not presently an issue, and can be left unchanged.
