### ISSUE TITLE
Operations chart not displaying data correctly

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#47]
After testing with a second set of data, there appears to be extra operations plotted when a treatment is selected, and the date labels are displaying incorrectly.

**Comment by jbrider** [comment]
It's in approval needed but it's a bug fix and not a pull request?

**Comment by MikeStower** [comment]
> It's in approval needed but it's a bug fix and not a pull request?

That was my way of saying it's done, I just haven't created a pull request for the change yet. Wasn't sure how to represent that through the project interface, didn't think it warranted another column.

**Comment by jbrider** [comment]
Why not do a pull request then?

**Comment by MikeStower** [comment]
I was going to do a few more fixes and bundle them in one pull, since it's only a one line change.

**Comment by jbrider** [comment]
I would much prefer 5 small one liners than 1 PR that changes 5 different pieces of code.

**Comment by jbrider** [comment]
The In Development currently has documentation in it... I thought you were working on exports?

**Comment by MikeStower** [comment]
I'm still deciding how to go about some of the export changes, so I've been polishing up the documentation as I'm thinking so that some concrete work is getting done.
