### ISSUE TITLE
How to handle factors when exporting to .apsimx

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#48]

**Comment by MikeStower** [comment]
Factors need to be matched with their corresponding APSIM model (i.e. through a lookup table), and the export has to then include variations on that model for each level (using the factorial model).

**Comment by MikeStower** [comment]
I've implemented this for both the Cultivar and Nitrogen factors, but I'm not sure how to handle Irrigation, since there's a lot of variance in the possible levels. 

The Density / Planting Date / Population / Row spacing factors all look I should just need to modify the Sowing script, so I'll working on that presently.

There's also a 'Treatment' factor, which I also don't know how to handle. It looks like a descriptive summary of a given treatment with no way to pull the data from it.

**Comment by jbrider** [comment]
I added a comment to the issue, but it prob should be out here.
A lookup table should be changeable - can you add a column to the level properties. 
When I say changeable - you would add it to the spreadsheet for reimporting.

**Comment by MikeStower** [comment]
So to clarify, each factor should have a specification, e.g.
```
public class Factor : IEntity
{
    public string Specification { get; set; }
}
```
and if that specification has no value assigned, the exporter uses the default value given. 

However, the user has the option to include a column to the spreadsheet, like so
![image](https://user-images.githubusercontent.com/53413135/111937271-15b8bc80-8b13-11eb-9799-8e575e8da7f8.png)
In which case the given specification will override the default value?

**Comment by jbrider** [comment]
The spreadsheet looks right, but is Factor the correct entity?
Aren't there multiple Levels for each factor?

**Comment by MikeStower** [comment]
The way it's set up in code at the moment one composite factor is created by combining the specification for the factor with each level in the factor, so the logic is `composite = factor.default_specification + level`. I was thinking to use the specification column to change that logic to `composite = factor.import_specification + level`.

If the specification column simply overrides the component completely, it would have to be entered into the sheet like
![image](https://user-images.githubusercontent.com/53413135/111938587-0d15b580-8b16-11eb-8e40-00a3965db0e2.png)
and would use the logic `composite = level.specification`, which I can also do, I just thought the first option was easier.

**Comment by jbrider** [comment]
You're assuming the level name is the value of the property being set - it doesn't allow for it to be a description.
Level should have it's own specification which makes the factor one redundant.
You have it right in the spreadsheet example on that last comment - that's how I would expect it to be provided so the user has control over how it is implemented.

**Comment by jbrider** [comment]
You should check out Drew's pull request: https://github.com/APSIMInitiative/ApsimX/pull/6240
It has the validation data set converted to experiments.
It would be good to be able to recreate them pretty similarly in our exports - you should have some of these as input data?

It would also be good to make sure it works with the latest .netcore3 version - this can wait until you have export working though.

**Comment by MikeStower** [comment]
Sounds like a good idea, I'll do a comparison of the Hermitage experiments and see how close I'm getting.

**Comment by MikeStower** [comment]
So I've had a bit of a look into this, it seems like Drew went one step further and has combined what REMS considers different experiments into the same model, making direct comparison difficult. He's joined all the Hermitage experiments into just two models, which probably isn't feasible in REMS without doing a bunch of work.

The Icrisat examples look more like what I'm after, but I don't have any input data for those experiments.

**Comment by hol430** [comment]
To add to this, the way that I've set up most of the experiments (with one composite factor per each combination of factors) isn't how you would normally do it in nextgen. You would normally want to use a permutations model with factor children (as in Lawes1996Early experiment in that Sorghum.apsimx file).

The Factorial.apsimx example file that's shipped with nextgen is also a useful reference for seeing all the different ways that factors can be set up in nextgen.

**Comment by MikeStower** [comment]
I think the permutation model works for our purposes; I've currently got it exporting something that looks like this,
![image](https://user-images.githubusercontent.com/53413135/112571963-e1a40b00-8e34-11eb-98b8-b1c6da7fbc3b.png)
where each of the composite factors has its own specification.

**Comment by hol430** [comment]
What's inside the composite factors? If it's only 1 line, then you can usually eliminate the composite factors by just using the parent factor specification:

![image](https://user-images.githubusercontent.com/36427516/112575570-49aa1f80-8e3c-11eb-9d7b-108fdc6dcc1d.png)

**Comment by MikeStower** [comment]
We're allowing for the user to override the default specifications, so we have to account for multiple lines unforunately. I could change the output based on the number of specifications detected, but it seems simpler to have one general solution.
