### ISSUE TITLE
Exported soil model contains no data

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#63]
The present soil model being exported is just a layout and contains no data for a simulation to use. To generate a running simulation will require the model to be populated with data.

**Comment by jbrider** [comment]
Is this because you have no example data to use?
If the simulation cannot be run, then the user should be presented with a report on what needs to be fixed in order to make it run.

**Comment by MikeStower** [comment]
In this case it's not set up to export that data yet, but we still need to account for a situation where that data might not be present, so we'll need that report as well.

**Comment by MikeStower** [comment]
So the soil export has been fixed such that it contains data where possible, now we just need to look at how we want to handle reporting missing data. Should there be some validation process similar to the import page, where the user is shown a preview of the export model, and invalid export options are highlighted? Or will a simple report / summary attached to the .apsimx file itself suffice.

**Comment by jbrider** [comment]
I would go with the 2nd option as it would be the easier and faster method?
The information should be the same.

**Comment by MikeStower** [comment]
Ok, I've started using memos that will appear in the exported file, giving export details. How detailed do we want the information to be? I was thinking to just list all the queries that were made during the export and saying whether the data was found or not.

Also, how fine-grained do we want the reporting? One giant summary for the whole file, one summary per experiment, or a memo per model that requires data (this should be the cleanest/simplest to actually implement)

**Comment by jbrider** [comment]
You are creating 1 apsim file - as a user, how likely do you think it will be that you are you going to read a memo for every model? Particularly if every one lists all the queries that were successfully written?

I would try a memo at the top of the file to tell the user what experiments are in the file and if there was any difficulty/missing data.  If you find incomplete met file data or soil data then you might need to ask the user if they want to attempt to export it or not.
