### ISSUE TITLE
Incomplete MET data when generating files

### ISSUE THREAD

**Issue by MikeStower** [QAAFI/REMS2020#65]
Simulations require MET data to run, but in some of the sample data there is no data to generate a .met file with.

Should the user be expected to resolve this themselves, or should a workaround be developed?

**Comment by jbrider** [comment]
If they haven't supplied the data, then they should be prompted for a file name for the met file.
They should be able to ignore that - at which point the met component should be added with no file name entered.

**Comment by MikeStower** [comment]
Prompted during the file export? Or are we relying on APSIM to tell them they need a .met file
